spring.application.name=parkingProject

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_db
spring.datasource.username=parking_user
spring.datasource.password=parking_password

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

parking.total-spaces=100
